---
dgi_members.settings:
  type: config_object
  label: 'DGI Members Settings'
  mapping:
    allow_compound_display_for_non_compound:
      type: boolean
      label: 'Allow non-Compound Object nodes to be displayed as Compound Objects.'
    display_non_compound_compound_as_first_member_of_itself:
      type: boolean
      label: 'Display compound non-Compound Object as first member of its set.'
    member_parameters:
      type: sequence
      label: 'The URL query parameters for which we will attempt to manage "active member" tokens.'
      sequence:
        type: string
        label: "A URL query parameter of interest."
    display_compound_object_metadata_by_default:
      type: boolean
      label: 'Default to displaying the metadata of the compound object rather than the metadata of the active member being viewed.'
